name: WorldDetection
version: '${project.version}'
main: fr.nono74210.worlddetection.WorldDetection
api-version: 1.19
authors: [ Nono74210 ]
description: Detect if a player is gathering resources in the wrong world to warn him
commands:
  detection:
    description: Base command
    permission: detection.reload
    aliases:
      - wd
      - wdetection
      - worlddetection
permissions:
  detection.bypass:
    description: Allows one to bypass the alerts
  detection.reload:
    description: Reload config file
    default: op
  detection.debug:
    description: Use the debug property of the plugin
    default: op
depend:
  - Multiverse-Core

